# Generated by Django 6.0.1 on 2026-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.TextField(default='Python Full Stack'),
            preserve_default=False,
        ),
    ]
